spring.application.name=wallet-service
spring.main.web-application-type=none
#server.port=8081
grpc.server.port=9091

spring.datasource.url=jdbc:postgresql://wallet-db:5432/wallet
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always