spring.application.name=order-service
grpc.client.wallet-service.address=static://wallet-service:9091
grpc.client.matcher-service.address=static://matcher-service:9091
grpc.client.wallet-service.negotiationType=plaintext
grpc.client.matcher-service.negotiationType=plaintext

spring.web.error.include-message=always

spring.datasource.url=jdbc:postgresql://order-db:5432/order
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=kafka:9092
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always